[package]
name = "DosStaticCollectible"
edition = "2024.beta"
license = "Cascade DOL"
authors = ["Cascade Foundation (dev@cascade.foundation)"]

[dependencies]

[addresses]
dos_static_collectible = "0x0"
