[package]
name = "DosStaticCollectible"
edition = "2024.beta"
license = "Cascade DOL"
authors = ["Cascade Foundation (dev@cascade.foundation)"]

[dependencies]
CascadeProtocol = { git = "https://github.com/cascadefoundation/cascade_protocol.git", subdir = "package",  rev = "testnet" }

[addresses]
dos_static_collectible = "0x0"
